GET http://localhost:3000/rackets

###
POST http://localhost:3000/rackets
Content-Type: application/json

{
	"description": "testing"
}

###
PATCH http://localhost:3000/rackets/39
Content-Type: application/json

{
	"description": "updating"
}